### ISSUE TITLE
BoB integration tasks

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#298]
IBM have forked BoB and are working on it. It'd be cool if there was some direct integration for working with BoB projects easier.

**Links**

* https://github.com/IBM/ibmi-bob
* https://github.com/edmundreinhardt/bob-recursive-example

**Tasks**

* [ ] Schema definitions for `.ibmi.json` and `.iproj.json`
* [ ] Built in Actions to run `makei` on the IFS
* [ ] Fetching the `EVFEVENT` file after `makei` has been run and displaying the errors

**Optional tasks**

* [ ] Ability to automatically generate `.iproj.json` (and maybe `.ibmi.json`)
* [ ] Tool to copy source members into a specific directory with the correct naming convention for `makei` (`NAME-TEXT_DESC.ext`)
* [ ] Tool to automatically detect dependencies append to `Rules.mk` 
* [ ] Update IBM's BoB wiki to match new functionality

**Comment by worksofliam** [comment]
Locked this issue as BoB has not yet been finalised and is potentially subject to change.

**Comment by worksofliam** [comment]
Closed for #291
